<script>// <![CDATA[
require(['jquery','base'],function($){
	$(document).ready(function(){ });
});

require(['jquery', 'flex'], function($) {
    $(document).ready(function($) {
         $('.flexslider-8').flexslider({
            animation: "fade",
            controlNav: "thumbnails",
            slideshowSpeed: 2000,
            minItems: 2,
            maxItems: 4
        });
    });
});
    // ]]>
</script>